import { describe, expect, it } from "vitest";
import { detectFileRole } from "../../clients/file-role.js";

describe("detectFileRole", () => {
	it("detects generated files from clawpatch-style filename patterns", () => {
		for (const filePath of [
			"proto/user.pb.go",
			"db/query_sqlc.go",
			"pkg/client_generated.go",
			"pkg/client_gen.go",
			"api/service_pb2.py",
			"api/service_pb2_grpc.py",
		]) {
			expect(detectFileRole(filePath)).toBe("generated");
		}
	});

	it("detects generated files from headers", () => {
		expect(
			detectFileRole(
				"src/client.ts",
				"// Code generated by tool. DO NOT EDIT.\nexport const x = 1;\n",
			),
		).toBe("generated");
	});
});
